admin:
  password: "$6$rounds=656000$ZOVspsCwH0q969yM$9G18yx4STUMnJsdDXLRfJ\
    qdbDLwe2gptkrRU4k9.O7nQctkY90vLWeWquYHprPNO1kBITenksXkhCTCiB2hGV1"
  full_name: Admin
  admin: true

predict:
  password: "$6$rounds=656000$ls/TQLvIaeoVDxdj$tbyHkJ53/2YkYQKPnm6yQ\
    kxDdy8zk3O.oPzHYSZ2dlX6UBsFLgnSBN4vEoTzoST/qpsk1ihoC8jQn4T.cAuI61"
  full_name: Predict
